### ISSUE TITLE
p- tags and space

### ISSUE THREAD

**Issue by seppzzz** [g4b0/silverstripe-htmlpurifier#5]
hi!
when using Purifier::PurifyTXT($do->$field)
its removing p - tags.
But :

```
<p>This is a test.</p>
<p>And another sentence.</p>
```

results in:

This is a test.And another sentence.

as you can see there is no space between those sentences.

How to fix this?
Thanks.
Sepp.

**Comment by g4b0** [comment]
Hi, 
in PurifiyTXT() docs: "Strip all HTML tags, like strip_tags, but encoding safe"

You can use Purify(), or write your wrapper extending class Purifier.
